
name: CI
env:
  NODE_VERSION: '10.x'   # set this to the node version to use

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: simple-lists.bilensky.ca
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: |
        npm install
        npm run build
